#!/usr/bin/env bash
# This script checks file properties for 'school'
if [ -e school ]; then
  echo "school file exists"
  if [ ! -s school ]; then echo "school file is empty"; else echo "school file is not empty"; fi
  [ -f school ] && echo "school is a regular file"
else
  echo "school file does not exist"
fi
